<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TeleMed.Application\TeleMed.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="EFCore.CheckConstraints" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Persistence\Seed\*.sql" LogicalName="Seed.%(Filename)%(Extension)" />
    <EmbeddedResource Include="Pdf\Assets\versalife-logo.png" LogicalName="Pdf.versalife-logo.png" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TeleMed.Api.IntegrationTests" />
    <InternalsVisibleTo Include="PrescriptionSample" />
  </ItemGroup>
</Project>
